cmake_minimum_required(VERSION 3.5)

function(report_failure verdict report)
  message(STATUS "CPU_LEARNER_VALIDATION verdict=${verdict} report=${report}")
  message(FATAL_ERROR "CPU learner validation failed: ${verdict}: ${report}")
endfunction()

function(extract_field line key output)
  if("${line}" MATCHES "(^| )${key}=([^ ]+)")
    set(${output} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  else()
    set(${output} "" PARENT_SCOPE)
  endif()
endfunction()

function(require_number value context)
  if(NOT "${value}" MATCHES "^-?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$")
    report_failure(OPERATIONAL_INCOMPLETE "${context} is not finite numeric data")
  endif()
endfunction()

function(math_true expression output)
  execute_process(
    COMMAND awk "BEGIN { if (${expression}) exit 0; exit 1 }"
    RESULT_VARIABLE result
    OUTPUT_QUIET ERROR_QUIET)
  if(result EQUAL 0)
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(audit_signature path stage verdict output)
  if(NOT EXISTS "${path}")
    report_failure(${verdict} "missing audit log ${path}")
  endif()
  file(STRINGS "${path}" records REGEX "^SMARTIES_NETWORK_AUDIT .*stage=${stage} ")
  if(NOT records)
    report_failure(${verdict} "missing ${stage} audit record in ${path}")
  endif()
  set(signature)
  foreach(record IN LISTS records)
    extract_field("${record}" network network)
    extract_field("${record}" digest digest)
    extract_field("${record}" finite finite)
    if(network STREQUAL "" OR NOT digest MATCHES "^[0-9a-fA-F]+$")
      report_failure(${verdict} "malformed ${stage} audit record in ${path}")
    endif()
    if(NOT finite STREQUAL "1")
      report_failure(NONFINITE_UPDATE "non-finite ${stage} audit record in ${path}")
    endif()
    list(APPEND signature "${network}=${digest}")
  endforeach()
  list(SORT signature)
  set(${output} "${signature}" PARENT_SCOPE)
endfunction()

function(read_metrics path prefix)
  if(NOT EXISTS "${path}")
    report_failure(OPERATIONAL_INCOMPLETE "missing evaluation metrics ${path}")
  endif()
  file(STRINGS "${path}" lines)
  list(LENGTH lines line_count)
  if(NOT line_count EQUAL 1)
    report_failure(OPERATIONAL_INCOMPLETE "evaluation metrics must contain exactly one record: ${path}")
  endif()
  list(GET lines 0 line)
  foreach(field seed episodes decisions mean_return action_mse finite)
    extract_field("${line}" ${field} value)
    if(value STREQUAL "")
      report_failure(OPERATIONAL_INCOMPLETE "metrics field ${field} missing from ${path}")
    endif()
    set(${prefix}_${field} "${value}" PARENT_SCOPE)
  endforeach()
  extract_field("${line}" seed seed)
  extract_field("${line}" episodes episodes)
  extract_field("${line}" decisions decisions)
  extract_field("${line}" mean_return mean_return)
  extract_field("${line}" action_mse action_mse)
  extract_field("${line}" finite finite)
  if(NOT seed STREQUAL "${EXPECTED_SEED}" OR
     NOT decisions STREQUAL "256" OR NOT finite STREQUAL "1")
    report_failure(OPERATIONAL_INCOMPLETE "evaluation identity/count/finite check failed in ${path}")
  endif()
  if(NOT episodes MATCHES "^[1-9][0-9]*$")
    report_failure(OPERATIONAL_INCOMPLETE "evaluation episode count is invalid in ${path}")
  endif()
  require_number("${mean_return}" "mean_return in ${path}")
  require_number("${action_mse}" "action_mse in ${path}")
endfunction()

function(validate_run run_dir prefix)
  set(training_log "${run_dir}/training/audit/learner_audit.log")
  if(NOT EXISTS "${training_log}")
    report_failure(UPDATE_NOT_OBSERVED "missing training audit log ${training_log}")
  endif()
  file(STRINGS "${training_log}" audit_records REGEX "^SMARTIES_NETWORK_AUDIT ")
  foreach(record IN LISTS audit_records)
    extract_field("${record}" finite finite)
    if(NOT finite STREQUAL "1")
      report_failure(NONFINITE_UPDATE "non-finite training audit record in ${training_log}")
    endif()
  endforeach()

  file(STRINGS "${training_log}" updates REGEX "^SMARTIES_NETWORK_AUDIT .*stage=update ")
  list(LENGTH updates update_count)
  if(NOT update_count EQUAL EXPECTED_UPDATES)
    report_failure(UPDATE_NOT_OBSERVED
      "expected ${EXPECTED_UPDATES} updates, observed ${update_count} in ${training_log}")
  endif()
  set(update_steps)
  foreach(record IN LISTS updates)
    extract_field("${record}" step step)
    if(NOT step MATCHES "^[1-9][0-9]*$")
      report_failure(UPDATE_NOT_OBSERVED "invalid update step in ${training_log}")
    endif()
    list(APPEND update_steps "${step}")
  endforeach()
  list(SORT update_steps COMPARE NATURAL ORDER ASCENDING)
  set(expected_step 1)
  foreach(step IN LISTS update_steps)
    if(NOT step EQUAL expected_step)
      report_failure(UPDATE_NOT_OBSERVED "missing or duplicate update step ${expected_step} in ${training_log}")
    endif()
    math(EXPR expected_step "${expected_step} + 1")
  endforeach()

  file(STRINGS "${training_log}" final_records
       REGEX "^SMARTIES_NETWORK_AUDIT .*stage=final ")
  if(NOT final_records)
    report_failure(UPDATE_NOT_OBSERVED "missing final optimizer audit in ${training_log}")
  endif()
  foreach(record IN LISTS final_records)
    extract_field("${record}" step final_step)
    if(NOT final_step STREQUAL "${EXPECTED_UPDATES}")
      report_failure(UPDATE_NOT_OBSERVED
        "final optimizer step ${final_step} differs from ${EXPECTED_UPDATES}")
    endif()
  endforeach()

  audit_signature("${training_log}" initialized CHECKPOINT_MISMATCH initial_signature)
  audit_signature("${training_log}" final CHECKPOINT_MISMATCH final_signature)
  audit_signature("${run_dir}/evaluation-initial/audit/learner_audit.log"
                  restart CHECKPOINT_MISMATCH restart_initial_signature)
  audit_signature("${run_dir}/evaluation-final/audit/learner_audit.log"
                  restart CHECKPOINT_MISMATCH restart_final_signature)
  if(NOT initial_signature STREQUAL restart_initial_signature OR
     NOT final_signature STREQUAL restart_final_signature)
    report_failure(CHECKPOINT_MISMATCH "evaluation restart digest differs from its saved checkpoint")
  endif()

  read_metrics("${run_dir}/evaluation-initial/metrics.txt" initial)
  read_metrics("${run_dir}/evaluation-final/metrics.txt" final)
  math_true("${final_action_mse} <= 0.5 * ${initial_action_mse}" mse_improved)
  math_true("${final_mean_return} >= 0.5 * ${initial_mean_return}" return_improved)
  if(NOT mse_improved OR NOT return_improved)
    report_failure(NO_SYNTHETIC_CONVERGENCE
      "final analytic-task error/return did not cover half the initial gap")
  endif()

  set(${prefix}_FINAL_MSE "${final_action_mse}" PARENT_SCOPE)
  set(${prefix}_FINAL_RETURN "${final_mean_return}" PARENT_SCOPE)
  set(${prefix}_FINAL_EPISODES "${final_episodes}" PARENT_SCOPE)
  set(${prefix}_FINAL_DECISIONS "${final_decisions}" PARENT_SCOPE)
endfunction()

if(NOT DEFINED ONE_RUN_DIR OR NOT IS_DIRECTORY "${ONE_RUN_DIR}")
  report_failure(OPERATIONAL_INCOMPLETE "ONE_RUN_DIR is missing")
endif()
if(NOT DEFINED EXPECTED_SEED OR NOT EXPECTED_SEED MATCHES "^[1-9][0-9]*$")
  report_failure(OPERATIONAL_INCOMPLETE "EXPECTED_SEED must be positive")
endif()
if(NOT DEFINED EXPECTED_UPDATES OR NOT EXPECTED_UPDATES MATCHES "^[1-9][0-9]*$")
  report_failure(OPERATIONAL_INCOMPLETE "EXPECTED_UPDATES must be positive")
endif()

validate_run("${ONE_RUN_DIR}" one)
if(DEFINED FOUR_RUN_DIR AND NOT FOUR_RUN_DIR STREQUAL "")
  if(NOT IS_DIRECTORY "${FOUR_RUN_DIR}")
    report_failure(OPERATIONAL_INCOMPLETE "FOUR_RUN_DIR is missing")
  endif()
  validate_run("${FOUR_RUN_DIR}" four)
  math_true("${four_FINAL_MSE} <= ${one_FINAL_MSE} + 0.02" cross_mse)
  math_true("((${four_FINAL_RETURN} * ${four_FINAL_EPISODES} / ${four_FINAL_DECISIONS}) - (${one_FINAL_RETURN} * ${one_FINAL_EPISODES} / ${one_FINAL_DECISIONS}) <= 0.02) && ((${one_FINAL_RETURN} * ${one_FINAL_EPISODES} / ${one_FINAL_DECISIONS}) - (${four_FINAL_RETURN} * ${four_FINAL_EPISODES} / ${four_FINAL_DECISIONS}) <= 0.02)" cross_return)
  if(NOT cross_mse OR NOT cross_return)
    report_failure(NO_SYNTHETIC_CONVERGENCE
      "four-thread final metrics differ from one-thread beyond the frozen tolerance")
  endif()
endif()

message(STATUS "CPU_LEARNER_VALIDATION verdict=PASS report=analytic-task learner update and checkpoint checks passed")
