if(NOT AWK_EXECUTABLE)
  find_program(AWK_EXECUTABLE NAMES awk gawk HINTS "C:/Program Files/Git/usr/bin")
endif()

function(eel_read_field line key output)
  string(REGEX MATCH "(^| )${key}=([^ ]+)" match "${line}")
  if(NOT match)
    set(${output} "" PARENT_SCOPE)
    return()
  endif()
  set(${output} "${CMAKE_MATCH_2}" PARENT_SCOPE)
endfunction()

function(eel_within_tolerance left right absolute relative output difference limit)
  execute_process(
    COMMAND "${AWK_EXECUTABLE}" -v "a=${left}" -v "b=${right}"
            -v "atol=${absolute}" -v "rtol=${relative}"
            "BEGIN { d=a-b; if (d<0) d=-d; aa=a; if (aa<0) aa=-aa;
                     bb=b; if (bb<0) bb=-bb; m=aa>bb?aa:bb;
                     lim=atol+rtol*m; printf \"%.17g %.17g %d\", d, lim, d<=lim; }"
    OUTPUT_VARIABLE result COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE " " ";" parts "${result}")
  list(GET parts 0 parsed_difference)
  list(GET parts 1 parsed_limit)
  list(GET parts 2 parsed_pass)
  set(${difference} "${parsed_difference}" PARENT_SCOPE)
  set(${limit} "${parsed_limit}" PARENT_SCOPE)
  if(parsed_pass EQUAL 1)
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

macro(eel_set_malformed verdict report detail)
  set(${verdict} "MALFORMED" PARENT_SCOPE)
  set(${report} "malformed: ${detail}" PARENT_SCOPE)
endmacro()

function(eel_record_field line key kind value_out error_out)
  string(REGEX MATCHALL "(^| )${key}=" occurrences "${line}")
  list(LENGTH occurrences occurrence_count)
  if(NOT occurrence_count EQUAL 1)
    set(${value_out} "" PARENT_SCOPE)
    set(${error_out} "${key} must occur exactly once" PARENT_SCOPE)
    return()
  endif()
  eel_read_field("${line}" "${key}" value)
  if(kind STREQUAL "integer")
    string(REGEX MATCH "^[0-9]+$" valid "${value}")
  else()
    string(REGEX MATCH "^[+-]?[0-9]+(\\.[0-9]+)?$" valid "${value}")
  endif()
  if("${valid}" STREQUAL "")
    set(${value_out} "" PARENT_SCOPE)
    set(${error_out} "${key} has nondecimal value '${value}'" PARENT_SCOPE)
    return()
  endif()
  set(${value_out} "${value}" PARENT_SCOPE)
  set(${error_out} "" PARENT_SCOPE)
endfunction()

function(eel_validate_record line record_type expected_decision expected_ranks expected_decisions error_out)
  if(record_type STREQUAL "STEP")
    set(fields
      "decision|integer" "environment_ranks|integer" "action|integer"
      "target_ratio|decimal" "previous_ratio|decimal" "applied_ratio|decimal"
      "start_time|decimal" "end_time|decimal" "ibamr_steps|integer"
      "start_com_x|decimal" "start_com_y|decimal" "end_com_x|decimal" "end_com_y|decimal"
      "displacement_x|decimal" "displacement_y|decimal" "forward_displacement|decimal"
      "forward_velocity|decimal" "phase_end|decimal" "lagrangian_points|integer"
      "reward_tracking|decimal" "reward_frequency|decimal" "reward_smoothness|decimal"
      "reward_total|decimal")
  else()
    set(fields
      "environment_ranks|integer" "decisions|integer" "ibamr_steps|integer"
      "elapsed_time|decimal" "displacement_x|decimal" "displacement_y|decimal"
      "forward_displacement|decimal" "final_phase|decimal" "lagrangian_points|integer"
      "reward_tracking|decimal" "reward_frequency|decimal" "reward_smoothness|decimal"
      "reward_total|decimal")
  endif()
  if(record_type STREQUAL "STEP")
    string(REGEX REPLACE "^EEL_FIXED_ACTION_STEP " "" payload "${line}")
  else()
    string(REGEX REPLACE "^EEL_FIXED_ACTION_SUMMARY " "" payload "${line}")
  endif()
  string(REPLACE " " ";" tokens "${payload}")
  foreach(token IN LISTS tokens)
    if(NOT token MATCHES "^[A-Za-z_][A-Za-z0-9_]*=[^ ]+$")
      set(${error_out} "trailing text '${token}'" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(field_spec IN LISTS fields)
    string(REPLACE "|" ";" field_parts "${field_spec}")
    list(GET field_parts 0 field)
    list(GET field_parts 1 kind)
    eel_record_field("${line}" "${field}" "${kind}" ignored field_error)
    if(field_error)
      set(${error_out} "${field_error}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  eel_read_field("${line}" "environment_ranks" ranks)
  if(NOT ranks STREQUAL "${expected_ranks}")
    set(${error_out} "environment_ranks expected ${expected_ranks}, got ${ranks}" PARENT_SCOPE)
    return()
  endif()
  eel_read_field("${line}" "lagrangian_points" points)
  if(NOT points STREQUAL "2932")
    set(${error_out} "lagrangian_points expected 2932, got ${points}" PARENT_SCOPE)
    return()
  endif()
  if(record_type STREQUAL "STEP")
    eel_read_field("${line}" "decision" decision)
    if(NOT decision STREQUAL "${expected_decision}")
      set(${error_out} "duplicate or out-of-order decision: expected ${expected_decision}, got ${decision}" PARENT_SCOPE)
      return()
    endif()
  else()
    eel_read_field("${line}" "decisions" decisions)
    if(NOT decisions STREQUAL "${expected_decisions}")
      set(${error_out} "summary decisions expected ${expected_decisions}, got ${decisions}" PARENT_SCOPE)
      return()
    endif()
  endif()
  set(${error_out} "" PARENT_SCOPE)
endfunction()

function(eel_collect_records stream steps_out summaries_out)
  string(REPLACE "\r\n" "\n" normalized "${stream}")
  string(REPLACE "\r" "\n" normalized "${normalized}")
  string(REPLACE "\n" ";" lines "${normalized}")
  set(steps)
  set(summaries)
  foreach(line IN LISTS lines)
    if(line MATCHES "^EEL_FIXED_ACTION_STEP ")
      list(APPEND steps "${line}")
    elseif(line MATCHES "^EEL_FIXED_ACTION_SUMMARY ")
      list(APPEND summaries "${line}")
    endif()
  endforeach()
  set(${steps_out} "${steps}" PARENT_SCOPE)
  set(${summaries_out} "${summaries}" PARENT_SCOPE)
endfunction()

function(eel_compare_field one_line two_line decision field category absolute relative verdict_out report_out)
  eel_read_field("${one_line}" "${field}" one_value)
  eel_read_field("${two_line}" "${field}" two_value)
  eel_within_tolerance("${one_value}" "${two_value}" "${absolute}" "${relative}" within difference limit)
  if(NOT within)
    set(${verdict_out} "${category}" PARENT_SCOPE)
    set(${report_out} "decision=${decision} field=${field} one=${one_value} two=${two_value} difference=${difference} tolerance=${limit}" PARENT_SCOPE)
    return()
  endif()
  set(${verdict_out} "" PARENT_SCOPE)
  set(${report_out} "" PARENT_SCOPE)
endfunction()

function(compare_eel_consistency_streams)
  cmake_parse_arguments(ARG "" "ONE_STREAM;TWO_STREAM;EXPECTED_DECISIONS;OUT_VERDICT;OUT_REPORT" "" ${ARGN})
  foreach(required ONE_STREAM TWO_STREAM EXPECTED_DECISIONS OUT_VERDICT OUT_REPORT)
    if(NOT DEFINED ARG_${required} OR "${ARG_${required}}" STREQUAL "")
      message(FATAL_ERROR "compare_eel_consistency_streams requires ${required}")
    endif()
  endforeach()
  if(NOT ARG_EXPECTED_DECISIONS MATCHES "^[0-9]+$" OR ARG_EXPECTED_DECISIONS LESS 1)
    eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "EXPECTED_DECISIONS must be a positive integer")
    return()
  endif()
  eel_collect_records("${ARG_ONE_STREAM}" one_steps one_summaries)
  eel_collect_records("${ARG_TWO_STREAM}" two_steps two_summaries)
  list(LENGTH one_steps one_step_count)
  list(LENGTH two_steps two_step_count)
  list(LENGTH one_summaries one_summary_count)
  list(LENGTH two_summaries two_summary_count)
  foreach(index RANGE 0 ${one_step_count})
    if(index LESS one_step_count)
      list(GET one_steps ${index} line)
      math(EXPR decision "${index} + 1")
      eel_validate_record("${line}" "STEP" "${decision}" "1" "${ARG_EXPECTED_DECISIONS}" record_error)
      if(record_error)
        eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "one stream ${record_error}")
        return()
      endif()
    endif()
  endforeach()
  foreach(index RANGE 0 ${two_step_count})
    if(index LESS two_step_count)
      list(GET two_steps ${index} line)
      math(EXPR decision "${index} + 1")
      eel_validate_record("${line}" "STEP" "${decision}" "2" "${ARG_EXPECTED_DECISIONS}" record_error)
      if(record_error)
        eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "two stream ${record_error}")
        return()
      endif()
    endif()
  endforeach()
  if(NOT one_step_count EQUAL ARG_EXPECTED_DECISIONS OR NOT two_step_count EQUAL ARG_EXPECTED_DECISIONS)
    eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "step count expected ${ARG_EXPECTED_DECISIONS}, got one=${one_step_count} two=${two_step_count}")
    return()
  endif()
  if(NOT one_summary_count EQUAL 1 OR NOT two_summary_count EQUAL 1)
    eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "summary count expected 1, got one=${one_summary_count} two=${two_summary_count}")
    return()
  endif()
  list(GET one_summaries 0 one_summary)
  list(GET two_summaries 0 two_summary)
  eel_validate_record("${one_summary}" "SUMMARY" "0" "1" "${ARG_EXPECTED_DECISIONS}" record_error)
  if(record_error)
    eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "one stream ${record_error}")
    return()
  endif()
  eel_validate_record("${two_summary}" "SUMMARY" "0" "2" "${ARG_EXPECTED_DECISIONS}" record_error)
  if(record_error)
    eel_set_malformed("${ARG_OUT_VERDICT}" "${ARG_OUT_REPORT}" "two stream ${record_error}")
    return()
  endif()

  set(exact_integer_fields action ibamr_steps)
  set(control_fields target_ratio previous_ratio applied_ratio start_time end_time phase_end)
  set(physical_fields start_com_x start_com_y end_com_x end_com_y displacement_x displacement_y forward_displacement forward_velocity)
  set(reward_fields reward_tracking reward_frequency reward_smoothness reward_total)
  set(control_absolute_tolerance "1e-12")
  set(control_relative_tolerance "1e-12")
  set(physical_absolute_tolerance "1e-10")
  set(physical_relative_tolerance "1e-8")
  foreach(index RANGE 0 ${ARG_EXPECTED_DECISIONS})
    if(index LESS ARG_EXPECTED_DECISIONS)
      list(GET one_steps ${index} one_line)
      list(GET two_steps ${index} two_line)
      math(EXPR decision "${index} + 1")
      foreach(field IN LISTS exact_integer_fields)
        eel_read_field("${one_line}" "${field}" one_value)
        eel_read_field("${two_line}" "${field}" two_value)
        if(NOT one_value STREQUAL two_value)
          set(${ARG_OUT_VERDICT} "PHYSICAL_MISMATCH" PARENT_SCOPE)
          set(${ARG_OUT_REPORT} "decision=${decision} field=${field} one=${one_value} two=${two_value} difference=exact tolerance=exact" PARENT_SCOPE)
          return()
        endif()
      endforeach()
      foreach(field IN LISTS control_fields)
        eel_compare_field("${one_line}" "${two_line}" "${decision}" "${field}" "PHYSICAL_MISMATCH" "${control_absolute_tolerance}" "${control_relative_tolerance}" comparison_verdict comparison_report)
        if(comparison_verdict)
          set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
          set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
      foreach(field IN LISTS physical_fields)
        eel_compare_field("${one_line}" "${two_line}" "${decision}" "${field}" "PHYSICAL_MISMATCH" "${physical_absolute_tolerance}" "${physical_relative_tolerance}" comparison_verdict comparison_report)
        if(comparison_verdict)
          set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
          set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
      foreach(field IN LISTS reward_fields)
        eel_compare_field("${one_line}" "${two_line}" "${decision}" "${field}" "REWARD_MISMATCH" "${physical_absolute_tolerance}" "${physical_relative_tolerance}" comparison_verdict comparison_report)
        if(comparison_verdict)
          set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
          set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
    endif()
  endforeach()
  eel_read_field("${one_summary}" "ibamr_steps" one_value)
  eel_read_field("${two_summary}" "ibamr_steps" two_value)
  if(NOT one_value STREQUAL two_value)
    set(${ARG_OUT_VERDICT} "PHYSICAL_MISMATCH" PARENT_SCOPE)
    set(${ARG_OUT_REPORT} "decision=${ARG_EXPECTED_DECISIONS} field=ibamr_steps one=${one_value} two=${two_value} difference=exact tolerance=exact" PARENT_SCOPE)
    return()
  endif()
  set(summary_control_fields elapsed_time final_phase)
  set(summary_physical_fields displacement_x displacement_y forward_displacement)
  foreach(field IN LISTS summary_control_fields)
    eel_compare_field("${one_summary}" "${two_summary}" "${ARG_EXPECTED_DECISIONS}" "${field}" "PHYSICAL_MISMATCH" "${control_absolute_tolerance}" "${control_relative_tolerance}" comparison_verdict comparison_report)
    if(comparison_verdict)
      set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
      set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(field IN LISTS summary_physical_fields)
    eel_compare_field("${one_summary}" "${two_summary}" "${ARG_EXPECTED_DECISIONS}" "${field}" "PHYSICAL_MISMATCH" "${physical_absolute_tolerance}" "${physical_relative_tolerance}" comparison_verdict comparison_report)
    if(comparison_verdict)
      set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
      set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(field IN LISTS reward_fields)
    eel_compare_field("${one_summary}" "${two_summary}" "${ARG_EXPECTED_DECISIONS}" "${field}" "REWARD_MISMATCH" "${physical_absolute_tolerance}" "${physical_relative_tolerance}" comparison_verdict comparison_report)
    if(comparison_verdict)
      set(${ARG_OUT_VERDICT} "${comparison_verdict}" PARENT_SCOPE)
      set(${ARG_OUT_REPORT} "${comparison_report}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${ARG_OUT_VERDICT} "PASS" PARENT_SCOPE)
  set(${ARG_OUT_REPORT} "all fields match" PARENT_SCOPE)
endfunction()
