if(NOT DEFINED COUPLING_ROOT)
  get_filename_component(COUPLING_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(ENVIRONMENT_HEADER "${COUPLING_ROOT}/cases/eel2d/EelEnvironment.h")
set(ENVIRONMENT_SOURCE "${COUPLING_ROOT}/cases/eel2d/EelEnvironment.cpp")
set(ADAPTER_SOURCE "${COUPLING_ROOT}/cases/eel2d/EelSmartiesAdapter.cpp")

foreach(FILE IN ITEMS "${ENVIRONMENT_HEADER}" "${ENVIRONMENT_SOURCE}" "${ADAPTER_SOURCE}")
  if(NOT EXISTS "${FILE}")
    message(FATAL_ERROR "required eel source is missing: ${FILE}")
  endif()
endforeach()

file(READ "${ENVIRONMENT_HEADER}" HEADER)
file(READ "${ENVIRONMENT_SOURCE}" ENVIRONMENT)
file(READ "${ADAPTER_SOURCE}" ADAPTER)

if(NOT HEADER MATCHES "void[ \\t\\r\\n]+writeVisualizationSnapshot[ \\t\\r\\n]*\\(")
  message(FATAL_ERROR "EelEnvironment does not expose a final visualization snapshot operation")
endif()
if(NOT ENVIRONMENT MATCHES "EelEnvironment::Impl::writeVisualizationSnapshot")
  message(FATAL_ERROR "EelEnvironment does not implement visualization snapshot output")
endif()
if(NOT ENVIRONMENT MATCHES "writePlotData[ \\t\\r\\n]*\\(")
  message(FATAL_ERROR "visualization snapshot implementation does not write plot data")
endif()

string(FIND "${ADAPTER}" "control_protocol_report.smarties_termination_received" TERMINATION_INDEX)
if(TERMINATION_INDEX EQUAL -1)
  message(FATAL_ERROR "normal Smarties termination lacks the final visualization lifecycle")
endif()
string(SUBSTRING "${ADAPTER}" ${TERMINATION_INDEX} -1 TERMINATION_TAIL)
string(FIND "${TERMINATION_TAIL}" "environment.writeVisualizationSnapshot();" SNAPSHOT_INDEX)
string(FIND "${TERMINATION_TAIL}" "environment.shutdown();" SHUTDOWN_INDEX)
if(SNAPSHOT_INDEX EQUAL -1 OR SHUTDOWN_INDEX EQUAL -1 OR SNAPSHOT_INDEX GREATER SHUTDOWN_INDEX)
  message(FATAL_ERROR "final visualization is not emitted after termination and before shutdown")
endif()

message(STATUS "eel final visualization contract passed")
